### ISSUE TITLE
Prometheus monitoring

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/operator#25]
**Describe the feature you'd like to have.**
It should be possible to monitor the Gluster cluster via prometheus

**What is the value to the end user? (why is it a priority?)**
Prometheus is **the** monitoring solution for Kubernetes, and as such, admins expect it to be the place to go for metrics about the services running in their infra. By providing statistics about the cluster, admins can be assured things are working well, or they know that they need to dig deeper.

**How will we know we have a good solution? (acceptance criteria)**
- Statistics about the Gluster cluster are available in Prometheus

**Work items**
- [ ] Create Prometheus endpoint
- [ ] Instrument operator actions and provide counts to prometheus endpoint
- [ ] Provide node uptime metrics
- [ ] Provide stats on storage assigned to Gluster

**Additional context**
We need to consider what data should come from the operator and what should come from the Gluster pods themselves or the CSI driver.
